import { Bebas_Neue } from "next/font/google";
import { Geist_Mono } from "next/font/google";

const BebasFont = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});
const GeistFont = Geist_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-mono",
});
import "./globals.css";
import Navigation from "@/components/Navigation";
export const metadata = {
  title: "CINEPLUSE | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${BebasFont.variable} ${GeistFont.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
